package config;

public class Database {

    public static String getSqlSchema() {
        return ""
                + "CREATE TABLE IF NOT EXISTS estados (\n"
                + "    id_estado INTEGER PRIMARY KEY AUTOINCREMENT,\n"
                + "    tipo TEXT,\n"
                + "    nombre TEXT\n"
                + ");\n"

                + "CREATE TABLE IF NOT EXISTS consolas (\n"
                + "    id_consola INTEGER PRIMARY KEY AUTOINCREMENT,\n"
                + "    nombre TEXT,\n"
                + "    abreviatura TEXT,\n"
                + "    anio INTEGER,\n"
                + "    fabricante TEXT,\n"
                + "    generacion TEXT,\n"
                + "    region TEXT,\n"
                + "    tipo TEXT,\n"
                + "    procesador TEXT,\n"
                + "    memoria TEXT,\n"
                + "    almacenamiento TEXT,\n"
                + "    frecuencia_mhz INTEGER,\n"
                + "    chip BOOLEAN,\n"
                + "    caracteristicas TEXT,\n"
                + "    fecha_lanzamiento TEXT,\n"
                + "    imagen TEXT,\n"
                + "    id_estado INTEGER,\n"
                + "    FOREIGN KEY (id_estado) REFERENCES estados(id_estado)\n"
                + ");\n"

                + "CREATE TABLE IF NOT EXISTS juegos (\n"
                + "    id_juegos INTEGER PRIMARY KEY AUTOINCREMENT,\n"
                + "    nombre TEXT,\n"
                + "    descripcion TEXT,\n"
                + "    desarrollador TEXT,\n"
                + "    editor TEXT,\n"
                + "    genero TEXT,\n"
                + "    modo_juego TEXT,\n"
                + "    fecha_lanzamiento TEXT,\n"
                + "    fecha_creacion_registro TEXT DEFAULT CURRENT_TIMESTAMP,\n"
                + "    id_estado INTEGER,\n"
                + "    es_recomendado BOOLEAN DEFAULT FALSE,\n"
                + "    imagen TEXT,\n"
                + "    video TEXT,\n"
                + "    FOREIGN KEY (id_estado) REFERENCES estados(id_estado)\n"
                + ");\n"

                + "CREATE TABLE IF NOT EXISTS juegos_consolas (\n"
                + "    id_juego INTEGER,\n"
                + "    id_consola INTEGER,\n"
                + "    PRIMARY KEY (id_juego, id_consola),\n"
                + "    FOREIGN KEY (id_juego) REFERENCES juegos(id_juegos),\n"
                + "    FOREIGN KEY (id_consola) REFERENCES consolas(id_consola)\n"
                + ");\n"

                + "CREATE TABLE IF NOT EXISTS votos (\n"
                + "    id_voto INTEGER PRIMARY KEY AUTOINCREMENT,\n"
                + "    id_juego INTEGER NOT NULL,\n"
                + "    jugabilidad INTEGER,\n"
                + "    dificultad INTEGER,\n"
                + "    diseno_niveles INTEGER,\n"
                + "    graficos INTEGER,\n"
                + "    sonido INTEGER,\n"
                + "    controles INTEGER,\n"
                + "    adiccion INTEGER,\n"
                + "    rejugabilidad INTEGER,\n"
                + "    valor_nostalgico INTEGER,\n"
                + "    innovacion INTEGER,\n"
                + "    diseno_visual INTEGER,\n"
                + "    multijugador_local INTEGER,\n"
                + "    comentarios TEXT,\n"
                + "    fecha_voto TEXT DEFAULT CURRENT_TIMESTAMP,\n"
                + "    FOREIGN KEY (id_juego) REFERENCES juegos(id_juegos)\n"
                + ");\n"

                + "CREATE TABLE IF NOT EXISTS dificultades_logros (\n"
                + "    id_dificultad INTEGER PRIMARY KEY AUTOINCREMENT,\n"
                + "    nombre TEXT\n"
                + ");\n"

                + "CREATE TABLE IF NOT EXISTS logros (\n"
                + "    id_logro INTEGER PRIMARY KEY AUTOINCREMENT,\n"
                + "    nombre TEXT,\n"
                + "    descripcion TEXT,\n"
                + "    horas_estimadas INTEGER,\n"
                + "    anio INTEGER,\n"
                + "    fecha_inicio TEXT,\n"
                + "    fecha_fin TEXT,\n"
                + "    intentos INTEGER,\n"
                + "    creditos INTEGER,\n"
                + "    puntuacion INTEGER,\n"
                + "    fecha_registro TEXT DEFAULT CURRENT_TIMESTAMP,\n"
                + "    id_juego INTEGER,\n"
                + "    id_estado INTEGER,\n"
                + "    id_dificultad INTEGER,\n"
                + "    id_consola INTEGER,\n"
                + "    FOREIGN KEY (id_juego) REFERENCES juegos(id_juegos),\n"
                + "    FOREIGN KEY (id_estado) REFERENCES estados(id_estado),\n"
                + "    FOREIGN KEY (id_dificultad) REFERENCES dificultades_logros(id_dificultad),\n"
                + "    FOREIGN KEY (id_consola) REFERENCES consolas(id_consola)\n"
                + ");\n"

                + "CREATE TABLE IF NOT EXISTS eventos (\n"
                + "    id_evento INTEGER PRIMARY KEY AUTOINCREMENT,\n"
                + "    titulo TEXT,\n"
                + "    descripcion TEXT,\n"
                + "    fecha_inicio TEXT,\n"
                + "    fecha_fin TEXT,\n"
                + "    hora_inicio TEXT,\n"
                + "    hora_fin TEXT,\n"
                + "    color TEXT,\n"
                + "    fondo TEXT,\n"
                + "    todo_el_dia BOOLEAN DEFAULT 0,\n"
                + "    recurrente TEXT,\n"
                + "    tipo_evento TEXT\n"
                + ");\n"

                + "CREATE TABLE IF NOT EXISTS metas_twitch (\n"
                + "    id_meta INTEGER PRIMARY KEY AUTOINCREMENT,\n"
                + "    descripcion TEXT,\n"
                + "    meta INTEGER,\n"
                + "    actual INTEGER DEFAULT 0,\n"
                + "    mes TEXT,\n"
                + "    anio INTEGER,\n"
                + "    fecha_inicio TEXT,\n"
                + "    fecha_fin TEXT,\n"
                + "    fecha_registro TEXT DEFAULT CURRENT_TIMESTAMP\n"
                + ");\n"

                + "CREATE TABLE IF NOT EXISTS anios_metas_twitch (\n"
                + "    id_meta INTEGER,\n"
                + "    anio INTEGER,\n"
                + "    PRIMARY KEY (id_meta, anio),\n"
                + "    FOREIGN KEY (id_meta) REFERENCES metas_twitch(id_meta)\n"
                + ");\n"

                + "CREATE TABLE IF NOT EXISTS seguidores (\n"
                + "    id_seguidores INTEGER PRIMARY KEY AUTOINCREMENT,\n"
                + "    cantidad INTEGER,\n"
                + "    fecha_registro TEXT DEFAULT CURRENT_TIMESTAMP\n"
                + ");\n"

                + "CREATE TABLE IF NOT EXISTS mejoras_canal (\n"
                + "    id_mejora INTEGER PRIMARY KEY AUTOINCREMENT,\n"
                + "    descripcion TEXT,\n"
                + "    fecha TEXT DEFAULT CURRENT_DATE\n"
                + ");\n"

                + "CREATE TABLE IF NOT EXISTS eventos_extensibles (\n"
                + "    id_extensible INTEGER PRIMARY KEY AUTOINCREMENT,\n"
                + "    motivo TEXT,\n"
                + "    fecha_evento TEXT\n"
                + ");\n"

                + "CREATE TABLE IF NOT EXISTS moderadores (\n"
                + "    id_moderador INTEGER PRIMARY KEY AUTOINCREMENT,\n"
                + "    nombre TEXT,\n"
                + "    email TEXT,\n"
                + "    fecha_alta TEXT,\n"
                + "    fecha_baja TEXT,\n"
                + "    id_estado INTEGER,\n"
                + "    FOREIGN KEY (id_estado) REFERENCES estados(id_estado)\n"
                + ");\n"

                + "CREATE TABLE IF NOT EXISTS metas_especificas (\n"
                + "    id_meta_especifica INTEGER PRIMARY KEY AUTOINCREMENT,\n"
                + "    descripcion TEXT,\n"
                + "    cumplida BOOLEAN DEFAULT 0,\n"
                + "    juegos_objetivo INTEGER,\n"
                + "    juegos_completados INTEGER,\n"
                + "    fabricante TEXT,\n"
                + "    id_consola INTEGER,\n"
                + "    fecha_inicio TEXT DEFAULT CURRENT_DATE,\n"
                + "    fecha_fin TEXT,\n"
                + "    fecha_registro TEXT DEFAULT CURRENT_TIMESTAMP,\n"
                + "    FOREIGN KEY (id_consola) REFERENCES consolas(id_consola)\n"
                + ");\n"

                + "CREATE TABLE IF NOT EXISTS anios_metas_especificas (\n"
                + "    id_meta_especifica INTEGER,\n"
                + "    anio INTEGER,\n"
                + "    PRIMARY KEY (id_meta_especifica, anio),\n"
                + "    FOREIGN KEY (id_meta_especifica) REFERENCES metas_especificas(id_meta_especifica)\n"
                + ");\n"

                + "CREATE TABLE IF NOT EXISTS configuracion_auxiliares (\n"
                + "    id_configuracion INTEGER PRIMARY KEY AUTOINCREMENT,\n"
                + "    nombre_visual TEXT NOT NULL,\n"
                + "    nombre_tabla TEXT NOT NULL,\n"
                + "    columna_id TEXT NOT NULL,\n"
                + "    columna_nombre TEXT NOT NULL\n"
                + ");\n";
    }
}
