package config;

/**
 * Clase que contiene el esquema SQL completo para la base de datos del diario
 * de videojuegos.
 */
public class Database {

    /**
     * Devuelve el esquema SQL como una cadena para crear todas las tablas
     * necesarias.
     *
     * @return Cadena con sentencias SQL CREATE TABLE.
     */
    public static String getSqlSchema() {
        return ""
                + "CREATE TABLE IF NOT EXISTS estados (\n"
                + "    id_estado INTEGER PRIMARY KEY AUTOINCREMENT,\n"
                + "    tipo TEXT NOT NULL,\n"
                + "    nombre TEXT NOT NULL\n"
                + ");\n"
                + "CREATE TABLE IF NOT EXISTS consolas (\n"
                + "    id_consola INTEGER PRIMARY KEY AUTOINCREMENT,\n"
                + "    nombre TEXT NOT NULL,\n"
                + "    abreviatura TEXT,\n"
                + "    anio INTEGER,\n"
                + "    fabricante TEXT,\n"
                + "    generacion TEXT,\n"
                + "    region TEXT,\n"
                + "    tipo TEXT,\n"
                + "    procesador TEXT,\n"
                + "    memoria TEXT,\n"
                + "    almacenamiento TEXT,\n"
                + "    frecuencia_mhz INTEGER,\n"
                + "    chip BOOLEAN,\n"
                + "    caracteristicas TEXT,\n"
                + "    fecha_lanzamiento TEXT,\n"
                + "    imagen TEXT,\n"
                + "    id_estado INTEGER,\n"
                + "    FOREIGN KEY (id_estado) REFERENCES estados(id_estado)\n"
                + ");\n"
                + "CREATE TABLE IF NOT EXISTS juegos (\n"
                + "    id_juegos INTEGER PRIMARY KEY AUTOINCREMENT,\n"
                + "    nombre TEXT NOT NULL,\n"
                + "    descripcion TEXT,\n"
                + "    desarrollador TEXT,\n"
                + "    editor TEXT,\n"
                + "    genero TEXT,\n"
                + "    modo_juego TEXT,\n"
                + "    fecha_lanzamiento TEXT,\n"
                + "    fecha_creacion_registro TEXT DEFAULT CURRENT_TIMESTAMP,\n"
                + "    id_estado INTEGER NOT NULL,\n"
                + "    es_recomendado BOOLEAN DEFAULT FALSE,\n"
                + "    imagen TEXT,\n"
                + "    video TEXT,\n"
                + "    FOREIGN KEY (id_estado) REFERENCES estados(id_estado)\n"
                + ");\n"
                + "CREATE TABLE IF NOT EXISTS juegos_consolas (\n"
                + "    id_juego INTEGER NOT NULL,\n"
                + "    id_consola INTEGER NOT NULL,\n"
                + "    PRIMARY KEY (id_juego, id_consola),\n"
                + "    FOREIGN KEY (id_juego) REFERENCES juegos(id_juegos),\n"
                + "    FOREIGN KEY (id_consola) REFERENCES consolas(id_consola)\n"
                + ");\n"
                + "CREATE TABLE IF NOT EXISTS votos (\n"
                + "    id_voto INTEGER PRIMARY KEY AUTOINCREMENT,\n"
                + "    id_juego INTEGER NOT NULL,\n"
                + "    voto INTEGER NOT NULL CHECK (voto >= 0 AND voto <= 10),\n"
                + "    criterio TEXT,\n"
                + "    fecha_voto TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,\n"
                + "    FOREIGN KEY (id_juego) REFERENCES juegos(id_juegos)\n"
                + ");\n"
                + "CREATE TABLE IF NOT EXISTS dificultades_logros (\n"
                + "    id_dificultad INTEGER PRIMARY KEY AUTOINCREMENT,\n"
                + "    nombre TEXT NOT NULL UNIQUE\n"
                + ");\n"
                + "CREATE TABLE IF NOT EXISTS logros (\n"
                + "    id_logro INTEGER PRIMARY KEY AUTOINCREMENT,\n"
                + "    nombre TEXT NOT NULL,\n"
                + "    descripcion TEXT,\n"
                + "    horas_estimadas INTEGER,\n"
                + "    anio INTEGER,\n"
                + "    fecha_inicio TEXT,\n"
                + "    fecha_fin TEXT,\n"
                + "    intentos INTEGER,\n"
                + "    creditos INTEGER,\n"
                + "    puntuacion INTEGER,\n"
                + "    fecha_registro TEXT DEFAULT CURRENT_TIMESTAMP,\n"
                + "    id_juego INTEGER NOT NULL,\n"
                + "    id_estado INTEGER NOT NULL,\n"
                + "    id_dificultad INTEGER,\n"
                + "    id_consola INTEGER NOT NULL,\n"
                + "    FOREIGN KEY (id_juego) REFERENCES juegos(id_juegos),\n"
                + "    FOREIGN KEY (id_estado) REFERENCES estados(id_estado),\n"
                + "    FOREIGN KEY (id_dificultad) REFERENCES dificultades_logros(id_dificultad),\n"
                + "    FOREIGN KEY (id_consola) REFERENCES consolas(id_consola)\n"
                + ");\n"
                + "CREATE TABLE IF NOT EXISTS eventos (\n"
                + "    id_evento INTEGER PRIMARY KEY AUTOINCREMENT,\n"
                + "    titulo TEXT NOT NULL,\n"
                + "    descripcion TEXT,\n"
                + "    fecha_inicio TEXT NOT NULL,\n"
                + "    fecha_fin TEXT,\n"
                + "    hora_inicio TEXT,\n"
                + "    hora_fin TEXT,\n"
                + "    color TEXT,\n"
                + "    fondo TEXT,\n"
                + "    todo_el_dia BOOLEAN DEFAULT 0,\n"
                + "    recurrente TEXT,\n"
                + "    tipo_evento TEXT\n"
                + ");\n"
                + "CREATE TABLE IF NOT EXISTS metas_twitch (\n"
                + "    id_meta INTEGER PRIMARY KEY AUTOINCREMENT,\n"
                + "    descripcion TEXT NOT NULL,\n"
                + "    meta INTEGER NOT NULL,\n"
                + "    fecha_inicio TEXT NOT NULL,\n"
                + "    fecha_fin TEXT,\n"
                + "    fecha_registro TEXT DEFAULT CURRENT_TIMESTAMP\n"
                + ");\n"
                + "CREATE TABLE IF NOT EXISTS seguidores (\n"
                + "    id_seguidores INTEGER PRIMARY KEY AUTOINCREMENT,\n"
                + "    cantidad INTEGER NOT NULL\n"
                + ");\n";
    }
}
